Repository prgrms-web-devcourse-final-project/WEB3_4_HelloWorld_FE, pull requests merged in 2025-04, with the labels that each got.

#11 feat(gym): 헬스장 페이지 디자인 (미완성)
  .eslintrc.json
  .github/PULL_REQUEST_TEMPLATE.md
  .vscode/settings.json
  README.md
  package.json
  postcss.config.js
  public/gym_sample.jpg
  public/map.png
  src/app/gym/page.tsx
  src/components/GymDetailPanel.tsx
  src/components/atoms/Button.tsx
  src/config/size.ts
  src/types/index.ts
  yarn.lock
Labels: improvement, backend-sync

#13 feat(triner):사장님 정보 등록록
  src/apis/trainerApi.ts
  src/components/templates/LoginTemplate/OwnerLoginForm/index.tsx
  src/utils/formatUtils.ts
Labels: common-feature, domain-refactor, new-feature, tests-passed

#14 feat(user):로그인 유저, 트레이너 정보 추가 가능/GYMMATE-253
  src/apis/userApi.ts
  src/components/molecules/AddressInput/index.tsx
  src/components/molecules/ExerciseInputs/index.tsx
  src/components/molecules/MeasurementInput/index.tsx
  src/components/templates/LoginTemplate/TrainerLoginForm/index.tsx
  src/components/templates/LoginTemplate/UserLoginOne/index.tsx
  src/components/templates/LoginTemplate/UserLoginTwo/index.tsx
  src/types/UserData.ts
Labels: needs-test, new-feature, backend-sync

#15 design(common): 메인페이지 완료
  package.json
  src/app/components/sections/MainGymMateSection.tsx
  src/app/components/sections/MainGymSection.tsx
  src/app/components/sections/MainPtSection.tsx
  src/app/components/sections/MainShopSection.tsx
  src/app/components/sections/MainVisualSection.tsx
  src/app/layout.tsx
  src/app/loading.tsx
  src/app/myfitness/page.tsx
  src/app/page.tsx
  src/components/atoms/Button.tsx
  src/components/atoms/KakaoMap.tsx
  src/components/atoms/Section.tsx
  src/components/molecules/Chart/BarChartTemplate.tsx
  src/components/molecules/Chart/index.tsx
  src/components/molecules/Main/MainGymCardItem.tsx
  src/components/molecules/Main/MainPtCard.tsx
  src/components/molecules/NumberCountCard.tsx
  src/components/molecules/Overlay.tsx
  src/components/molecules/ShopProductItem.tsx
  src/components/molecules/StarGroup.tsx
  src/components/molecules/Wave.tsx
  src/components/organisms/Footer.tsx
  src/components/organisms/Header.tsx
  src/components/organisms/Main/MainSection.tsx
  src/components/templates/MainLayout.tsx
  src/components/templates/navbar.tsx
  src/config/icons.tsx
  src/hooks/useKaKaoLoader.ts
  src/stores/calendarStore.ts
  src/types/index.ts
  src/utils/animations.ts
  src/utils/apiConfig.ts
  src/utils/formatter.ts
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: ui-ux, new-feature, multiple-file-changes

#16 fix(user):member 정보등록 수정
  src/apis/userApi.ts
  src/components/templates/LoginTemplate/UserLoginOne/index.tsx
  src/components/templates/LoginTemplate/UserLoginTwo/index.tsx
Labels: bugfix, new-feature

#17 feat(user) : 유저 타입 저장-GYMMATE-274
  src/apis/userTypeApi.ts
  src/app/login/components/HomeLink/index.tsx
  src/app/login/components/ProgressBar/index.tsx
  src/app/login/page.tsx
  src/app/membermypage/page.tsx
  src/app/page.tsx
  src/components/atoms/TabItem.tsx
  src/components/molecules/mypage/MypageTaps.tsx
  src/components/molecules/mypage/TabList.tsx
  src/components/templates/MemberMypageTemplate/index.tsx
  src/stores/memberTypeStore.ts
  src/utils/userType.tsx
Labels: improvement, new-feature, backend-sync

#18 disign(user) : 맴버 마이페이지 퍼블리싱/GYMMATE-275
  src/app/membermypage/page.tsx
  src/components/atoms/BirthSelect/index.tsx
  src/components/atoms/TabItem.tsx
  src/components/molecules/OpenDateInputGroup/index.tsx
  src/components/molecules/mypage/MypageTaps.tsx
  src/components/molecules/mypage/TabList.tsx
  src/components/organisms/MyPage/UserForm.tsx
  src/components/templates/MemberMypageTemplate/CouponListHistory.tsx
  src/components/templates/MemberMypageTemplate/HistoryList.tsx
  src/components/templates/MemberMypageTemplate/Logout.tsx
  src/components/templates/MemberMypageTemplate/index.tsx
  src/types/UserData.ts
Labels: ui-ux, improvement, no-impact, multiple-file-changes

#19 design(gym): 제휴 헬스장 등록 페이지 디자인
  package.json
  public/gym/icons/cloth.svg
  public/gym/icons/healthboy.jpg
  public/gym/icons/inbody.svg
  public/gym/icons/locker.svg
  public/gym/icons/parking.svg
  public/gym/icons/sauna.svg
  public/gym/icons/shower.svg
  public/gym/icons/towel.svg
  public/gym/icons/wifi.svg
  src/app/mypage/gym/edit/page.tsx
  src/components/atoms/Button.tsx
  src/components/atoms/FacilityButton.tsx
  src/components/atoms/NumberInputBase.tsx
  src/components/atoms/TextareaBase.tsx
  src/components/templates/MainLayout.tsx
  yarn.lock
Labels: ui-ux

#23 Gym/design/gymmate 224
  package-lock.json
  package.json
  src/app/mypage/gym/edit/page.tsx
  src/components/GymDetailPanel.tsx
  src/components/atoms/Button.tsx
  src/components/atoms/FacilityButton.tsx
  src/components/molecules/GymIntroSection.tsx
  src/components/molecules/GymTabs.tsx
  yarn.lock
Labels: ui-ux

#24 shop(feat) : 상품 샵 퍼블리싱 및 aip 연동/GYMMATE-280
  .gitignore
  next.config.js
  src/apis/naverShoppingApi.ts
  src/app/api/naver/search/route.ts
  src/app/shop/[id]/page.tsx
  src/app/shop/page.tsx
  src/components/atoms/SelectedChips.tsx
  src/components/templates/ShopTemplate/DetailTemplate.tsx
  src/components/templates/ShopTemplate/FilterCheckboxList.tsx
  src/components/templates/ShopTemplate/FilterSidebar.tsx
  src/components/templates/ShopTemplate/ProductList.tsx
  src/components/templates/ShopTemplate/index.tsx
  src/types/naver.d.ts
Labels: ui-ux, new-feature, multiple-file-changes, tests-passed

#25 refactor(FE) : 파일 이름 위치 변경/GYMMATE-293
  src/app/login/components/BankSelect.tsx
  src/app/login/components/CustomButton.tsx
  src/app/login/components/HomeLink/HomeReturnMsg.tsx
  src/app/login/components/HomeLink/RedirectHomeText.tsx
  src/app/login/components/InputField.tsx
  src/app/login/components/LoginTab.tsx
  src/app/login/components/ProgressBar.tsx
  src/app/login/components/SocialLoginButton.tsx
  src/app/myfitness/components/CalenderCards.tsx
  src/app/myfitness/page.tsx
  src/components/atoms/BirthSelect.tsx
  src/components/atoms/GenderSelector.tsx
  src/components/atoms/RadioButton.tsx
  src/components/atoms/ScrollShadowBox.tsx
  src/components/molecules/AddressInput.tsx
  src/components/molecules/AddressSearchModal.tsx
  src/components/molecules/BirthdayInputGroup.tsx
  src/components/molecules/Calendar.tsx
  src/components/molecules/ExerciseInputs.tsx
  src/components/molecules/GenderRadioGroup.tsx
  src/components/molecules/LoginTemplatesForm/Header.tsx
  src/components/molecules/LoginTemplatesForm/ProgressWrapper.tsx
  src/components/molecules/LoginTemplatesForm/StepTrainer.tsx
  src/components/molecules/LoginTemplatesForm/StepUser.tsx
  src/components/molecules/LoginTemplatesForm/StepZero.tsx
  src/components/molecules/MeasurementInput.tsx
  src/components/molecules/OpenDateInputGroup.tsx
  src/components/templates/LoginTemplate/OwnerLoginForm.tsx
  src/components/templates/LoginTemplate/TrainerLoginForm.tsx
  src/components/templates/LoginTemplate/TrainerTemplate.tsx
  src/components/templates/LoginTemplate/UserLoginOne.tsx
  src/components/templates/LoginTemplate/UserLoginTwo.tsx
  src/components/templates/ScheduleView/CalenderView.tsx
  src/components/templates/ScheduleView/index.tsx
Labels: rebuild, multiple-file-changes, global-refactor

#26 refactor(FE) : 빌드 에러 수정
  src/apis/trainerApi.ts
  src/apis/userApi.ts
  src/app/api/naver/search/route.ts
  src/app/login/components/BankSelect.tsx
  src/app/login/components/CustomButton.tsx
  src/app/login/components/HomeLink/HomeReturnMsg.tsx
  src/app/login/components/HomeLink/RedirectHomeText.tsx
  src/app/login/components/InputField.tsx
  src/app/login/components/LoginTab.tsx
  src/app/login/components/ProgressBar.tsx
  src/app/login/components/SocialLoginButton.tsx
  src/app/myfitness/components/CalenderCards.tsx
  src/components/atoms/BirthSelect.tsx
  src/components/atoms/GenderSelector.tsx
  src/components/atoms/LevelBadge.tsx
  src/components/atoms/RadioButton.tsx
  src/components/molecules/BirthdayInputGroup.tsx
  src/components/molecules/Calendar.tsx
  src/components/organisms/MyPage/UserForm.tsx
  src/components/templates/LoginTemplate/OwnerLoginForm.tsx
  src/components/templates/LoginTemplate/TrainerLoginForm.tsx
  src/components/templates/LoginTemplate/UserLoginTwo.tsx
  src/components/templates/MemberMypageTemplate/Logout.tsx
  src/components/templates/ScheduleView/index.tsx
  src/components/templates/ShopTemplate/DetailTemplate.tsx
  src/components/templates/ShopTemplate/ProductList.tsx
  src/hooks/useAuth.ts
  src/stores/authStore.ts
  src/utils/userType.tsx
  yarn.lock
Labels: typo-fix, rebuild, execution-ok, multiple-file-changes, minor-bug

#27 feat(user) : 일반 유저 정보 조회 및 수정/GYMMATE-298
  src/apis/userApi.ts
  src/components/molecules/AddressInput.tsx
  src/components/organisms/MyPage/UserForm.tsx
Labels: new-feature, backend-sync

#28 disign(point) : 결제페이지 퍼블리싱/GYMMATE-300
  public/assets/images/pointpage.jpg
  public/assets/images/pointpagesub.jpg
  src/app/point/page.tsx
  src/components/templates/PointTemplate/PointHeader.tsx
  src/components/templates/PointTemplate/PointPlanSection.tsx
  src/components/templates/PointTemplate/index.tsx
Labels: ui-ux, optional, no-impact, execution-ok, tests-passed, backend-sync

#30 fix(FE): 에러수정/GMYMATE-308
  src/components/atoms/BirthSelect.tsx
  src/components/molecules/Calendar.tsx
Labels: bugfix, rebuild

#31 fix(user) : 버그 수정/GYMMATE-310
  src/app/login/components/BankSelect.tsx
  src/components/atoms/BirthSelect.tsx
  src/components/molecules/BirthdayInputGroup.tsx
  src/components/molecules/Chart/LineChartTemplate.tsx
  src/components/molecules/Chart/PieChartTemplate.tsx
  src/components/molecules/GenderRadioGroup.tsx
  src/components/molecules/LoginTemplatesForm/StepTrainer.tsx
  src/components/molecules/LoginTemplatesForm/StepUser.tsx
  src/components/templates/LoginTemplate/OwnerLoginForm.tsx
  src/components/templates/LoginTemplate/TrainerLoginForm.tsx
  src/components/templates/LoginTemplate/UserLoginOne.tsx
  src/components/templates/LoginTemplate/UserLoginTwo.tsx
  src/components/templates/LoginTemplate/index.tsx
  src/components/templates/ShopTemplate/FilterSidebar.tsx
Labels: hotfix, bugfix, rebuild, critical-bug

#33 feat(myfitness) : 운동 일지 생성/GYMMATE-315
  src/apis/diaryApi.ts
  src/components/molecules/Calendar.tsx
  src/components/templates/ScheduleView/CalendarWithModal.tsx
  src/components/templates/ScheduleView/ModalView.tsx
  src/components/templates/ScheduleView/index.tsx
  src/types/diary.ts
Labels: ui-ux, new-feature, tests-passed

#34 design(pt): PT 상세페이지 완료
  .gitignore
  src/app/pt/[trainerId]/reservation/page.tsx
  src/components/atoms/CheckBox.tsx
  src/components/molecules/GYM/GymListCardItem.tsx
  src/components/molecules/PT/PtCardSection.tsx
  src/components/molecules/PT/PtProductDetailItem.tsx
  src/components/molecules/PT/PtReviewItem.tsx
  src/components/molecules/Tabs.tsx
  src/components/organisms/PT/PtProductDetail.tsx
  src/components/organisms/ScheduleTimeCheckGroup.tsx
  src/constants/pt_schedules.ts
  src/types/pt.types.ts
Labels: ui-ux

#35 feat(myfitness) : 나의 일지 삭제, 버그 수정/GYMMATE-318
  src/apis/diaryApi.ts
  src/components/templates/ScheduleView/CalenderView.tsx
  src/stores/calendarStore.ts
Labels: bugfix, new-feature, tests-passed

#37 design(gym): 상세정보 디자인 완료 /GYMMATE-224
  .env
  public/gym/review/profile1.jpg
  public/gym/review/profile2.jpg
  public/gym/review/review1.jpg
  public/gym/review/review2.jpg
  public/gym/review/review3.jpg
  public/gym/review/review4.jpg
  public/gym/review/review5.jpg
  src/components/GymDetailPanel.tsx
  src/components/molecules/EquipmentSection.tsx
  src/components/molecules/GymReviewCard.tsx
  src/components/molecules/GymReviewSection.tsx
  src/components/molecules/GymTrainerSection.tsx
Labels: ui-ux

#39 fix(FE) : 파일 경로 수정/GYMMATE-326
  src/app/api/naver/search/route.ts
Labels: bugfix, minor-bug

#40 feat(user) : 회원 탈퇴 및 경로 수정/GYMMATE-327
  src/apis/userApi.ts
  src/components/molecules/Chart/BarChartTemplate.tsx
  src/components/molecules/Chart/LineChartTemplate.tsx
  src/components/molecules/Chart/PieChartTemplate.tsx
  src/components/molecules/Chart/index.tsx
  src/components/templates/MemberMypageTemplate/Logout.tsx
  src/components/templates/MemberMypageTemplate/index.tsx
  src/components/templates/ScheduleView/ModalView.tsx
Labels: bugfix, ui-ux, new-feature

#42 feat(common) : 헤더 푸터 경로 수정/GYMMATE-328
  src/components/organisms/Footer.tsx
  src/components/organisms/Header.tsx
Labels: ui-ux, new-feature, tests-passed

#45 feat(user) : 회원가입시 헬스장 리스트 보여주기기/GYMMATE-348
  src/apis/gymApi.ts
  src/components/templates/LoginTemplate/Modal.tsx
  src/components/templates/LoginTemplate/TrainerLoginForm.tsx
  src/types/gym.ts
Labels: bugfix, ui-ux, new-feature

#46 feat(gym) : 헬스장 이용권 사용현황 확인/GYMMATE-349
  src/apis/gymTicketsApi.ts
  src/components/molecules/Table.tsx
  src/components/organisms/MyPage/UserForm.tsx
  src/components/templates/MemberMypageTemplate/CouponListHistory.tsx
  src/components/templates/MemberMypageTemplate/index.tsx
  src/types/gymTicket.ts
  src/utils/mapGymTicketsToCommonHistory.ts
Labels: ui-ux, new-feature, tests-passed

#47 fix(FE) : 로그인 사장님 부분 수정/GYMMATE-351
  src/apis/trainerApi.ts
  src/components/templates/LoginTemplate/OwnerLoginForm.tsx
Labels: bugfix, typo-fix

#48 fix(shop) : shop 수정정/GYMMATE-355
  src/components/templates/ShopTemplate/ProductList.tsx
  src/components/templates/ShopTemplate/index.tsx
Labels: ui-ux, new-feature

#49 PT(feat) : 유저 PT 등록내역 확인 가능/GYMMATE-376
  src/apis/reservationApi.ts
  src/app/(main)/membermypage/components/Table.tsx
  src/components/templates/MemberMypageTemplate/HistoryList.tsx
  src/components/templates/MemberMypageTemplate/index.tsx
  src/types/reservation.ts
  src/utils/convertReservationToHistory.ts
Labels: needs-test, new-feature, backend-sync

#51 feat(FE) : 트레이너 마이페이지 헤더 수정/GYMMATE-392
  src/apis/userApi.ts
  src/components/organisms/TrainerHeader.tsx
Labels: new-feature

#50 feat(gym): 헬스장 페이지 지도 및 길찾기 기능 구현
  public/gym/icons/mapmarker.png
  public/gym/icons/mapmarker.svg
  src/app/(main)/gym/page.tsx
  src/components/GymDetailPanel.tsx
  src/components/RoutePanel.tsx
  src/constants/dummyGymDetailData.ts
Labels: new-feature

#52 fix(FE): 상태관리 복구구/GYMMATE-393
  src/app/(main)/login/page.tsx
  src/app/layout.tsx
  src/components/templates/ScheduleView/index.tsx
  src/stores/memberTypeStore.ts
  src/utils/AuthInitializer.tsx
  src/utils/userType.tsx
Labels: bugfix, new-feature, critical-bug

#55 disign(FE) : alert창 수정, 위치 변경/GYMMATE-396
  src/app/providers.tsx
  src/components/organisms/MyPage/UserForm.tsx
  src/components/templates/LoginTemplate/OwnerLoginForm.tsx
  src/components/templates/LoginTemplate/TrainerLoginForm.tsx
  src/components/templates/LoginTemplate/UserLoginTwo.tsx
  src/components/templates/MemberMypageTemplate/Logout.tsx
  src/components/templates/ScheduleView/CalenderView.tsx
  src/components/templates/ScheduleView/ModalView.tsx
  src/components/templates/ScheduleView/index.tsx
Labels: common-feature, new-feature

#56 feat(trainer): 링크연결
  package-lock.json
  package.json
  src/apis/ptApi.ts
  src/app/(main)/components/sections/MainPtSection.tsx
  src/app/(main)/pt/[trainerId]/reservation/page.tsx
  src/app/(main)/pt/page.tsx
  src/app/(trainer)/layout.tsx
  src/app/(trainer)/mypage/edit/page.tsx
  src/app/(trainer)/mypage/page.tsx
  src/app/(trainer)/mypage/pt/page.tsx
  src/app/(trainer)/mypage/pt/pttime/page.tsx
  src/app/(trainer)/mypage/pt/registerpt/page.tsx
  src/app/loading.tsx
  src/app/providers.tsx
  src/components/molecules/Main/MainPtCard.tsx
  src/components/molecules/PT/PtCardList.tsx
  src/components/molecules/PT/PtCardSection.tsx
  src/components/molecules/PT/PtProductItem.tsx
  src/components/organisms/Header.tsx
  src/components/organisms/PT/PtProduct.tsx
  src/components/organisms/PT/PtProductDetail.tsx
  src/components/organisms/TrainerMypage/Dashboard.tsx
  src/components/templates/LoginTemplate/index.tsx
  src/components/templates/TrainerLayoutTemplate.tsx
  src/hooks/useInitUser.ts
  src/middleware.ts
  src/stores/memberTypeStore.ts
  src/stores/testAuthStore.ts
  src/utils/apiInstance.ts
  src/utils/formatter.ts
  yarn.lock
Labels: ui-ux, minor-refactor, execution-ok, multiple-file-changes

#57 feat(FE) : 트레이너 헤더 수정, 탈퇴 폼 수정/GYMMATE-400
  src/components/molecules/ConfirmDrawer.tsx
  src/components/organisms/TrainerHeader.tsx
  src/components/templates/MemberMypageTemplate/Logout.tsx
Labels: new-feature

#58 feat(toss) : 결제 연결/GYMMATE-402
  package.json
  src/app/(main)/payment/fail/page.tsx
  src/app/(main)/payment/success/page.tsx
  src/components/templates/PointTemplate/PointHeader.tsx
  src/components/templates/PointTemplate/index.tsx
  yarn.lock
Labels: new-feature, tests-passed, backend-sync

#59 feat(myfitness) : 3대 통합 조회 및 ui 수정/GYMATE-419
  src/apis/bigthreeApi.ts
  src/app/(main)/login/components/CustomButton.tsx
  src/app/(main)/myfitness/page.tsx
  src/components/molecules/Chart/BarChartTemplate.tsx
  src/components/molecules/Chart/LineChartTemplate.tsx
  src/components/molecules/Chart/PieChartTemplate.tsx
  src/components/molecules/Chart/index.tsx
  src/components/templates/ScheduleView/index.tsx
  src/types/bigthree.ts
  src/utils/bigThree.ts
Labels: ui-ux, new-feature, tests-passed

#60 disign(toss) : 결제 성공 실패 페이지 퍼블리싱/GYMMATE-420
  src/app/(main)/payment/fail/page.tsx
  src/app/(main)/payment/success/page.tsx
Labels: ui-ux

#62 fix(FE) : 트레이너 헤더 수정/GYMAMTE-432
  src/components/organisms/TrainerHeader.tsx
  src/components/templates/PointTemplate/index.tsx
  src/components/templates/ScheduleView/index.tsx
Labels: bugfix

#61 feat(gym): 길찾기 패널 기능 및 디자인 구현중 /GYMMATE-206
  public/gym/routepanel/bus.svg
  public/gym/routepanel/subway.svg
  public/gym/routepanel/walk.svg
  src/app/(main)/gym/page.tsx
  src/app/test/route/page.tsx
  src/components/GymDetailPanel.tsx
  src/components/RoutePanel.tsx
  src/components/RoutePanelTest.tsx
Labels: ui-ux, new-feature

#63 design(FE) : 파비콘 변경/GMYMATE-434
  public/favicon.ico
Labels: ui-ux

#67 feat(gym): api 연결, 지도 및 길찾기 /GYMMATE-206
  package.json
  public/gym/icons/newmapmarker.svg
  src/apis/gymApi.ts
  src/app/(main)/gym/page.tsx
  src/assets/lottie/empty.json
  src/components/GymDetailPanel.tsx
  src/components/RoutePanel.tsx
  src/components/molecules/GymTrainerCard.tsx
  src/components/molecules/GymTrainerSection.tsx
  src/constants/dummyGymDetailData.ts
  src/types/gym.ts
  src/types/lottie.d.ts
  src/utils/time.ts
  yarn.lock
Labels: ui-ux, new-feature

#68 feat(pt): 리뷰 등록 구현 메인 지도 연결 예약기능
  src/app/(main)/components/sections/MainGymSection.tsx
  src/app/(main)/gym/page.tsx
  src/app/(main)/pt/[trainerId]/reservation/page.tsx
  src/app/(main)/pt/complete/page.tsx
  src/app/(main)/pt/page.tsx
  src/app/(trainer)/mypage/edit/page.tsx
  src/app/(trainer)/mypage/reservation/page.tsx
  src/app/(trainer)/mypage/userlist/page.tsx
  src/components/atoms/KakaoMap.tsx
  src/components/atoms/ThumbsSwiper.tsx
  src/components/molecules/Main/MainPtCard.tsx
  src/components/molecules/ModalImageGallery.tsx
  src/components/molecules/PT/PtReviewItem.tsx
  src/components/molecules/TrainerMypage/StudentCard.tsx
  src/components/organisms/PT/PtProductDetail.tsx
  src/components/organisms/ScheduleTimeCheckGroup.tsx
  src/components/organisms/TrainerMypage/AwardForm.tsx
  src/components/organisms/TrainerMypage/Dashboard.tsx
  src/components/templates/GymPage.tsx
  src/hooks/useAwardMutation.ts
  src/hooks/useStudentMutation.ts
  src/types/gym.ts
  src/types/review.ts
  src/types/student.ts
  src/utils/apiInstance.ts
Labels: ui-ux, rebuild, minor-refactor, new-feature, multiple-file-changes

#72 FE(design) : 다크모드 수정/GYMMATE-448
  src/components/GymDetailPanel.tsx
  src/components/atoms/FacilityButton.tsx
  src/components/molecules/GymIntroSection.tsx
  src/components/molecules/GymReviewCard.tsx
  src/components/molecules/GymTimeFeeSection.tsx
  src/components/molecules/GymTrainerCard.tsx
  src/components/molecules/GymTrainerSection.tsx
  src/components/templates/GymPage.tsx
Labels: ui-ux

#76 feat(toss) : 모든 버튼 연결/GYMMATE-453
  src/app/(main)/payment/success/page.tsx
  src/components/templates/PointTemplate/PointHeader.tsx
  src/components/templates/PointTemplate/PointPlanSection.tsx
  src/hooks/useTossPayment.ts
Labels: new-feature, tests-passed

#78 feat(common): 메인 짐메이트 애니에이션 수정/GYMMATE-395
  src/app/(main)/components/sections/MainGymMateSection.tsx
  src/app/(main)/components/sections/MainPtSection.tsx
  src/components/molecules/Main/MainPtCard.tsx
  src/components/molecules/NumberCountCard.tsx
  src/components/organisms/TrainerMypage/Dashboard.tsx
  src/utils/animations.ts
  tailwind.config.js
Labels: ui-ux, new-feature

#79 fix(pt) PT 마이페이지 버그 수정 / GYMMATE-395
  src/app/(trainer)/mypage/userlist/page.tsx
  src/components/molecules/Main/MainPtCard.tsx
  src/components/organisms/PT/PtProductDetail.tsx
  src/components/organisms/TrainerMypage/AwardForm.tsx
  src/components/templates/PtTemplate/PtReservationForm.tsx
Labels: hotfix, bugfix

#80 fix(member) : 유저 레벨 반영/GYMMATE-454
  src/components/organisms/MyPage/UserForm.tsx
  src/types/UserData.ts
Labels: bugfix

#84 Fix(gym): 평점 없는 헬스장 오류 수정
  src/components/templates/GymPage.tsx
Labels: bugfix
