Repository prgrms-web-devcourse-final-project/WEB3_4_HelloWorld_FE, pull requests merged in 2025-03, with the labels that each got.

#2 design(common): 헤더 푸터 퍼블리싱 완료
  .cursor/rules/FERules.mdc
  .vscode/settings.json
  src/app/layout.tsx
  src/components/templates/LoginTemplate/index.tsx
  src/components/templates/footer.tsx
  src/components/templates/navbar.tsx
  src/config/hero_ui_config.ts
Labels: ui-ux, common-feature, new-feature

#3 병합충돌해결
  .cursor/rules/FERules.mdc
  .vscode/settings.json
  src/app/layout.tsx
  src/components/templates/LoginTemplate/index.tsx
  src/components/templates/footer.tsx
  src/components/templates/navbar.tsx
  src/config/hero_ui_config.ts
Labels: hotfix, bugfix

#5 design(trainer): 트레이너 ui 작업
  package.json
  src/app/login/components/BankSelect/index.tsx
  src/app/login/components/HomeLink/HomeReturnMsg/index.tsx
  src/app/login/components/LoginTab/index.tsx
  src/app/login/components/ProgressBar/index.tsx
  src/components/atoms/GenderSelector/index.tsx
  src/components/molecules/LoginTemplatesForm/Header/index.tsx
  src/components/molecules/LoginTemplatesForm/ProgressWrapper/index.tsx
  src/components/molecules/LoginTemplatesForm/StepTrainer/index.tsx
  src/components/molecules/LoginTemplatesForm/StepUser/index.tsx
  src/components/molecules/LoginTemplatesForm/StepZero/index.tsx
  src/components/molecules/OpenDateInputGroup/index.tsx
  src/components/templates/LoginTemplate/OwnerLoginForm/index.tsx
  src/components/templates/LoginTemplate/TrainerLoginForm/index.tsx
  src/components/templates/LoginTemplate/TrainerTemplate/index.tsx
  src/components/templates/LoginTemplate/UserLoginOne/index.tsx
  src/components/templates/LoginTemplate/UserLoginTwo/index.tsx
  src/components/templates/LoginTemplate/index.tsx
  yarn.lock
Labels: ui-ux, common-feature, new-feature, multiple-file-changes, dependency-update

#6 disign(myfitness) : 캘린더 ui 임시
  package.json
  src/app/myfitness/page.tsx
  src/components/atoms/ScrollShadowBox/index.tsx
  src/components/molecules/Calendar/index.tsx
  src/components/templates/ScheduleView/index.tsx
  src/stores/calendarStore.ts
  src/types/schedule.ts
  src/utils/dateUtils.ts
  src/utils/dayjsSetup.ts
  tailwind.config.js
  yarn.lock
Labels: ui-ux, improvement, multiple-file-changes

#8 User/feat/gymmate 소셜 로그인 테스트
  .env
  src/app/login/components/SocialLoginButton/index.tsx
  src/components/molecules/Calendar/index.tsx
  src/components/molecules/LoginTemplatesForm/StepZero/index.tsx
  src/components/templates/LoginTemplate/index.tsx
  src/hooks/useAuth.ts
  src/stores/authStore.ts
  src/utils/apiConfig.ts
Labels: needs-test, new-feature

#9 feat(trainer) : 트레이너 소셜 로그인
  src/components/molecules/LoginTemplatesForm/StepTrainer/index.tsx
  src/components/templates/LoginTemplate/OwnerLoginForm/index.tsx
  src/components/templates/LoginTemplate/TrainerLoginForm/index.tsx
  src/components/templates/LoginTemplate/index.tsx
Labels: bugfix, new-feature, backend-sync
